version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: challenge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: